<?php
  $title="Login Page|mipow Admin";
  $this->headTitle($title);
?>
<div id="login-box" class="login-box visible widget-box no-border">
    <div class="widget-main">
        <h4 class="header">Please Enter Your Information</h4>
        <?php
            $form->setAttribute('method', 'post');
            $form->setAttribute('action', $this->url('user-login'));
        ?>
        <?php
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <div class="row">
            <?php $username = $form->get('username'); ?>
            <?php echo $this->formLabel($username); ?>
            <?php echo $this->formelement($username); ?>

            <div><?php
                $elementError = $this->formelementErrors()
                    ->setMessageOpenFormat('<div class="help-block">')
                    ->setMessageSeparatorString('</div><div class="help-block">')
                    ->setMessageCloseString('</div>');
                echo $elementError->render($username);
                ?></div>
        </div>
        <div class="row">
            <?php $password = $form->get('password'); ?>
            <?php echo $this->formLabel($password); ?>
            <?php echo $this->formelement($password); ?>
            <div><?php echo $elementError->render($password); ?></div>
        </div>
        <div class="">
            <?php echo $this->formelement($form->get("login")); ?>
        </div>
        <?php
        echo $this->form()->closeTag();
        ?>
        </div>
 </div>
</body>