<?php
echo $this->doctype();
?>
<html lang="en">

<head>
    <?php
    $this->headMeta()->setCharset('UTF-8')->appendHttpEquiv('Cache-Control', 'no-cache')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName("description", "")
        ->appendName("author", "");
    echo $this->headMeta();
    echo $this->headTitle("AdminPage")->setSeparator("|")->setAutoEscape(false);
    $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath() . '/img/mipow.ico'), 'PREPEND')
        ->appendStylesheet($this->basePath("media/css/bootstrap.min.css"))
        ->appendStylesheet($this->basePath('media/css/bootstrap-responsive.min.css'))
        ->appendStylesheet($this->basePath('media/css/font-awesome.min.css'))
        ->appendStylesheet($this->basePath('media/css/style-metro.css'))
        ->appendStylesheet($this->basePath('media/css/style.css'))
        ->appendStylesheet($this->basePath('media/css/style-responsive.css'))
        ->appendStylesheet($this->basePath('media/css/default.css'));

    echo $this->headLink();

    $this->headScript()->appendFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))

        ->appendFile($this->basePath("media/js/jquery-ui-1.10.1.custom.min.js"))
        ->appendFile($this->basePath('media/js/excanvas.min.js'), 'text/javascript', array('conditional' => 'lt IE9'))
        ->appendFile($this->basePath('media/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE9'));
    echo $this->headScript();

    ?>
    <script src="/media/js/app.js" type="text/javascript"></script>
    <?php $this->headStyle()->captureStart(); ?>
    .jqstooltip {
    position: absolute;
    left: 0px;
    top: 0px;
    visibility: hidden;
    background: rgb(0, 0, 0) transparent;
    background-color: rgba(0, 0, 0, 0.6);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000);
    -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000)";
    color: white;
    font: 10px arial, san serif;
    text-align: left;
    white-space: nowrap;
    padding: 5px;
    border: 1px solid white;
    z-index: 10000;
    }
    .jqsfield {
    color: white;
    font: 10px arial, san serif;
    text-align: left;
    }
    .jqstooltip {
    position: absolute;
    left: 0px;
    top: 0px;
    visibility: hidden;
    background: rgb(0, 0, 0) transparent;
    background-color: rgba(0, 0, 0, 0.6);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000);
    -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000)";
    color: white;
    font: 10px arial, san serif;
    text-align: left;
    white-space: nowrap;
    padding: 5px;
    border: 1px solid white;
    z-index: 10000;
    }
    .jqsfield {
    color: white;
    font: 10px arial, san serif;
    text-align: left;
    }
    .brand img{
    height:30px;
    }
    <?php $this->headStyle()->captureEnd(); ?>
</head>


<body class="page-header-fixed" style="">
<div class="header navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">

        <div class="container-fluid">
            <a class="brand" href="index.html">
                <img src="<?php echo $this->basePath('img/logo.png'); ?>" alt="logo">
            </a>
            <a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
                <img src="<?php echo $this->basePath('media/image/menu-toggler.png'); ?>" alt="">
            </a>
            <ul class="nav pull-right">
                <li class="dropdown user open">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img alt="" src="<?php echo $this->basePath('media/image/avatar1_small.jpg'); ?>">
                        <span class="username">Bob Nilson</span>
                        <i class="icon-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="divider"></li>
                        <li><a href="extra_lock.html"><i class="icon-lock"></i> Lock Screen</a></li>
                        <li><a href="login.html"><i class="icon-key"></i> Log Out</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar nav-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <ul class="page-sidebar-menu">
            <li>
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                <div class="sidebar-toggler hidden-phone"></div>
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
            </li>
            <li>
                <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
                <form class="sidebar-search">
                    <div class="input-box">
                        <a href="javascript:;" class="remove"></a>
                        <input type="text" placeholder="Search...">
                        <input type="button" class="submit" value=" ">
                    </div>
                </form>
                <!-- END RESPONSIVE QUICK SEARCH FORM -->
            </li>
            <li class="start active ">
                <a href="<?php echo $this->url('admin-index'); ?>">
                    <i class="icon-home"></i>
                    <span class="title">Dashboard</span>
                    <span class="selected"></span>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('admin-file');?>"><i class="icon-file"></i><span class="title"><?php echo $this->translate("File Manager"); ?></span></a>
            </li>
            <li class="">
                <a href="javascript:;">
                    <i class="icon-briefcase"></i>
                    <span class="title">Pages Manager</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu" style="display: none;">
                    <li>
                        <a href="<?php echo $this->url('admin-front-pages'); ?>"><i class="halflings-icon home"></i>Home</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('admin-front-pages',array('action'=>'category'));?>"><i class="icon-sitemap"></i>Category</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('admin-front-pages',array('action'=>'product'));?>"><i class="icon-barcode"></i>Product page</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('admin-front-pages',array('action'=>'doclist'));?>"><i class="icon-cogs"></i>Document lists</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('admin-front-pages',array('action'=>'detail'));?>"><i class="icon-cogs"></i>Detail</a>
                    </li>
                </ul>
            </li>
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
    <!-- BEGIN PAGE -->
    <div class="page-content">
        <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
        <div id="portlet-config" class="modal hide">
            <div class="modal-header">
                <button data-dismiss="modal" class="close" type="button"></button>
                <h3>Widget Settings</h3>
            </div>
            <div class="modal-body">
                Widget settings form goes here
            </div>
        </div>
        <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
        <!-- BEGIN PAGE CONTAINER-->
        <?php echo $this->content; ?>
        <!-- END PAGE CONTAINER-->
    </div>
    <!-- END PAGE -->
</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
<div class="footer">
    <div class="footer-inner">

    </div>
    <div class="footer-tools">
			<span class="go-top">
			<i class="icon-angle-up"></i>
			</span>
    </div>
</div>

<!-- END PAGE LEVEL SCRIPTS -->
<script>
    jQuery(document).ready(function () {
        App.init(); // initlayout and core plugins

    });
</script>
<!-- END BODY -->
</div>
</body>
</html>