<div class="navheader">
    <div class="center catnav container">
        <?php echo $this->partial('category\nav'); ?>
        <div class="schsidebar"><?php echo $this->partial('search\global'); ?></div>
    </div>
</div>
<div class="wp">
    <div class="wh container">
        <ul class="header-tiper breadcrumb">
            <li><a href="<?php echo $this->url('home'); ?>"><?php echo $this->translate('Home'); ?></a></li>
            <li>
                <a href="<?php echo $this->url('category', array('id' => $category->c_id)); ?>"><?php echo $category->c_code; ?></a>
            </li>
            <li><a href="<?php //echo $this->url('product',array('id'));?>"><?php ?><?php echo $category['sku']; ?></a>
            </li>
        </ul>
    </div>
    <div class="container">
        <img
            src="<?php echo $this->basepath('images/' . $category['c_folder'] . '/' . $category['sku'] . '/' . $category['sku'] . '-waller.png'); ?>">
    </div>
    <div class="container">
        <div>
            <div class="p-info">
                <div class="p-img"><img
                        src="<? echo $this->basepath('images/' . $category['c_folder'] . '/' . $category['sku'] . '/' . $category['sku'] . '.png'); ?>">
                </div>
                <div class="p-sel"><span class="col"></span><span class="col"></span><span class="col"></span><span
                        class="col"></span></div>
            </div>
            <div class="doc-info">
                <table>
                    <tr>
                        <th></th>
                        <th></th>
                    </tr>
                    <tr>
                       <td><?php echo $this->translate("document name");?></td><td><?php echo $detail['d_code']; ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('document belong to category');?></td><td><?php echo $category['c_code']; ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('document belong to product');?></td><td><?php  ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate("document type");?></td><td><?php echo $detail['down_type_code']; ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate("last updated time");?></td><td><?php echo $detail['d_updatetime']; ?></td>
                    </tr>
                </table>
                <div class="d_side">
                   <a href="<?php echo $this->url('download',array('id'=>$detail['p_id']));?>">download</a>
                    </div>
            </div>
        </div>
    </div>