<div class="row-fluid span12">
    <form action="{$this->url('admin-front-pages',['action'=>'product'])}" class="form-horizontal">
        <div class="control-group">
            <label class="control-label">{$this->translate("product")}</label>
            <div class="controls">
                <input type="text" value="smart power"/>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">{$this->translate("banner")}</label>
            <div class="controls">
                <img src="{$this->basePath('/images/')}"/>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button class="btn blue">更换图片</button>
            </div>
        </div>
    </form>
</div>