{$this->doctype()}
<html lang="en">
<head>
    <meta charset="utf-8">

    {$this->headTitle("mipow得到")->setSeparator(" - ")->setAutoEscape(false)}
    {$this->headMeta()->appendName("viewport", "width=device-width,
    initial-scale=1.0")->appendHttpEquiv("X-UA-Compatible", "IE=edge")}


    {*Le styles*}
    {$this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => "{$this->basePath()}
    /img/mipow.ico"] )
    ->prependStylesheet("{$this->basePath()}/css/style.css")
    ->prependStylesheet("{$this->basePath()}/css/bootstrap-theme.min.css")
    ->prependStylesheet("{$this->basePath()}/css/bootstrap.min.css")
    ->prependStylesheet("{$this->basePath()}/css/front.css")}

    <!-- Scripts -->
    {$this->headScript()
     ->prependFile("{$this->basepath()}/js/down.js")
    ->prependFile("{$this->basePath()}/js/bootstrap.min.js")
    ->prependFile("{$this->basePath()}/js/jquery.min.js")
    ->prependFile("{$this->basePath()}/js/respond.min.js", 'text/javascript', ['conditional' => 'lt IE 9'])
    ->prependFile("{$this->basePath()}/js/html5shiv.js", 'text/javascript', ['conditional' => 'lt IE 9'])}

</head>
<body>
<div class="nav-container">
    <div class="container">
        <a href="{$this->url('home')}" class="navbar-brand"><img
                src="{$this->basepath('img/logo.png')}"></a>

        <div class="languages">
            {$this->checklang()}
        </div>
    </div>
</div>
<div class="" id="main">

{$this->content}
    <hr>
    <footer>
        <p>&copy; 2005 - {date('Y')} by Zend Technologies
            Ltd. {$this->translate('All rights reserved.')}</p>
    </footer>
</div>
<!-- /container -->
{$this->inlineScript()}
</body>
</html>
