{$this->doctype()}
<html lang="en">
<head>
    {$this->headMeta()->setCharset('UTF-8')->appendHttpEquiv('Cache-Control', 'no-cache')
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendName("description", "")
    ->appendName("author", "")}
    {$this->headTitle("AdminPage")->setSeparator("|")->setAutoEscape(false)}
    {$this->headLink(['rel' => 'shortcut icon', 'href' => '$this->basePath()/img/mipow.ico'], 'PREPEND')

    ->appendStylesheet($this->basePath("media/css/bootstrap.min.css"))
    ->appendStylesheet($this->basePath('media/css/style.css'))
    ->appendStylesheet($this->basePath('media/css/bootstrap-responsive.min.css'))
    ->appendStylesheet($this->basePath('css/admin.css'))

    ->appendStylesheet($this->basePath('media/css/default.css'))
    ->appendStylesheet($this->basePath('media/css/font-awesome.min.css'))
    ->appendStylesheet($this->basePath('media/css/style-responsive.css'))}


    {$this->headScript()->appendFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
    ->appendFile($this->basePath("media/js/jquery-ui-1.10.1.custom.min.js"))
    ->appendFile($this->basePath('media/js/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE9'])
    }
    <script src="/media/js/app.js" type="text/javascript"></script>
    {$this->headStyle()->captureStart()}

    {$this->headStyle()->captureEnd()}
</head>


<body class="page-header-fixed" style="">
<div class="header navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="brand" href="{$this->url('admin-index')}">
                <img src="{$this->basePath('img/logo.png')}" alt="logo">
            </a>
            <a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
                <img src="{$this->basePath('media/image/menu-toggler.png')}" alt="">
            </a>
            <ul class="nav pull-right">
                <li class="dropdown user">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img alt="" src="{$this->basePath('media/image/avatar1_small.jpg')}">
                        <span class="username">Bob Nilson</span>
                        <i class="icon-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="divider"></li>
                        <li><a href="login.html"><i class="icon-key"></i> Log Out</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar nav-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        {$this->navigation('navigation')->menu()->setPartial('admin\layout\partial')}

        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
    <!-- BEGIN PAGE -->
    <div class="page-content">
        <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
        <div id="portlet-config" class="modal hide">
            <div class="modal-header">
                <button data-dismiss="modal" class="close" type="button"></button>
                <h3>Widget Settings</h3>
            </div>
            <div class="modal-body">
                Widget settings form goes here
            </div>
        </div>
        <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
        <!-- BEGIN PAGE CONTAINER-->

        {$this->content}

        <!-- END PAGE CONTAINER-->
    </div>
    <!-- END PAGE -->
</div>

<!-- END PAGE LEVEL SCRIPTS -->
<script>
    jQuery(document).ready(function () {
        App.init(); // initlayout and core plugins

    });
</script>
<!-- END BODY -->
</div>
</body>
</html>