<div class="navheader">
    <div class="center catnav container">
        <?php echo $this->partial('category\nav'); ?>
        <div class="schsidebar"><?php echo $this->partial('search\global'); ?></div>
    </div>
</div>
<div class="wp">
    <div class="wh container">
     <ul class="header-tiper breadcrumb">
         <li><a href="<?php echo $this->url('home');?>"><?php echo $this->translate('Home');?></a></li>
        <li><a href="<?php echo $this->url('category',array('id'=>$category->c_id));?>"><?php echo $category->c_code;?></a></li>
         <li><a href="<?php //echo $this->url('product',array('id'));?>"><?php ?><?php echo $product['sku'];?></a></li>
     </ul>
    </div>
    <div class="container">

        <img src="<?php echo $this->basepath('images/'.$category['c_folder'].'/'.$category['sku'].'/'.$category['sku'].'-top.png');?>">
    </div>
    <div id="doc-list" class="doc-list container">
     <table class="table table-bordered table-responsive">
         <tbody>
         <tr>
             <th><?php echo $this->translate("filename");?></th>
             <th><?php echo $this->translate("language");?></th>
             <th><?php echo $this->translate("url");?></th>
             <th><?php echo $this->translate("update time");?></th>
             <th><?php echo $this->translate("file type");?></th>
             <th><?php echo $this->translate("download");?></th>
         </tr>
         </tbody>
         <tbody class="dl">
         <?php foreach($paginator as $doc):?>
             <tr data-url="<?php echo $this->url('detail',array('id'=>$doc['d_id']));?>">
                 <td><?php echo $doc['d_code'];?></td>
                 <td><?php echo $doc['name'];?></td>
                 <td><?php echo $doc['d_url'];?></td>
                 <td><?php echo $doc['d_updatetime'];?></td>
                 <td><?php echo $doc['down_type_code'];?></td>
                 <td><a href="<?php echo $this->url('download',array('id'=>$doc['d_id']));?>"><?php echo $this->translate('download');?></a></td>
             </tr>
         <?php endforeach;?>
         </tbody>
         </table>
</div>
<div class="container">
    <?php echo $this->paginationControl($this->paginator,'Sliding','paginator\control',array('id'=>$category['p_id'],'lang'=>$lang,'route'=>'product'));?>
</div>
    </div>
