{if  $this->pageCount}
<ul class="pagination">
{if isset($this->previous)}
            <li><a href="{$this->url($route,['id'=>$id,'lang'=>$lang,'page'=>$this->previous])}">Pervious</a></li>
{/if}
    {if $this->pageCount>1}
      {foreach $this->pagesInRange  as $page}
        {if $page!==$this->current}
            <li><a href="{$this->url($route,['id'=>$id,'lang'=>$lang,'page'=>$page])}">{$page}</a></li>
                {else}
                <li class="active"><a href="{$this->url($route,['id'=>$id,'lang'=>$lang,'page'=>$page])}">{$page}</a></li>
            {/if}
      {/foreach}
{/if}

    {if isset($this->next)}
        <li><a href="{$this->url($route,['id'=>$id,'lang'=>$lang,'page'=>$this->next])}">Next</a></li>
       {/if}
</ul>
  {/if}