<option value=""><a href="{$this->url('category',['id'=>$id,'page'=>$curPage])}">
        <span>{$this->translate('each page show 5 items')}</span></a>
</option>
<option value=""><a href="{$this->url('category',['id'=>$id,'page'=>$curPage])}">
        <span>{$this->translate('each page show 10 items')}</span></a>
</option>
<option value=""><a href="{$this->url('category',['id'=>$id,'page'=>$curPage])}">
        <span>{$this->translate('each page show 15 items')}</span></a>
</option>
<option value=""><a href="{$this->url('category',['id'=>$id,'page'=>$curPage])}">
        <span>{$this->translate('each page show 20 items')}</span></a>
</option>
<option value=""><a href="{$this->url('category',['id'=>$id,'page'=>$curPage])}">
        <span>{$this->translate('show all items')}</span></a>
</option>