<?php
return array(
    'controllers'=>array(
        'invokables'=>array(
            'User\Controller\Login'=> 'User\Controller\LoginController',
            'User\Controller\User'=> 'User\Controller\UserController',
        ),
        'abstract_factories'=>array(
            'User\Service\AbstractFactory\AuthAbstractFactory'
        )
    ),
    'router'=>array(
        'routes'=>array(
            'user-login'=>array(
                'type'=>'segment',
                'options'=>array(
                    'route'=>'[/:lang]/login.html',
                    'constraints'=>array(
                      'lang'=>'[a-zA-Z]{2}'
                    ),
                    'defaults'=>array(
                        '__NAMESPACE__'=>'User\Controller',
                        'controller'=>'User\Controller\login',
                        'action'=>'login'
                    )
                ),
            ),
            'user-logout'=>array(
                'type'=>'segment',
                'options'=>array(
                    'route'=>'[/:lang]/logout',
                    'constraints'=>array(
                        'lang'=>'[a-zA-Z]{2}'
                    ),
                    'defaults'=>array(
                        '__NAMESPACE__'=>'User\Controller',
                        'controller'=>'User\Controller\login',
                        'action'=>'logout'
                    )
                ),
            ),
            'user-center'=>array(
                'type'=>'segment',
                'options'=>array(
                    'route'=>'[/:lang]/user[/:action]',
                    'constraints'=>array(
                        'lang'=>'[a-zA-Z]{2}',
                    ),
                    'defaults'=>array(
                        '__NAMESPACE__'=>'User\Controller',
                        'controller'=>'User\Controller\User',
                        'action'=>'logout'
                    )
                )
            )
        ),
    ),
    'view_manager'=>array(
        'template_path_stack'=>array(
            __DIR__.'/../view',
        ),
        'template_map'=>array(
            'user-layout'=> __DIR__.'/../view/layout/user-layout.phtml'
        )
    ),
    'service_manager'=>array(
          'factories'=>array(
              'Auth'=>'User\Service\Factories\AuthFactory'
          )
    )
);