<?php if($this->pageCount):?>
<ul class="pagination">
<?php if(isset($this->previous)):?>
            <li><a href="<?php echo $this->url($route,array('id'=>$id,'lang'=>$lang,'page'=>$this->previous));?>">Pervious</a></li>
<?php endif;?>
    <?php if($this->pageCount>1):?>
      <?php foreach($this->pagesInRange  as $page):?>
        <?php if($page!==$this->current):?>
            <li><a href="<?php echo $this->url($route,array('id'=>$id,'lang'=>$lang,'page'=>$page));?>"><?php echo $page;?></a></li>
                <?php else: ?>
                <li class="active"><a href="<?php echo $this->url($route,array('id'=>$id,'lang'=>$lang,'page'=>$page));?>"><?php echo $page;?></a></li>
            <?php endif;?>
      <?php endforeach;?>
<?php endif; ?>

    <?php if(isset($this->next)):?>
        <li><a href="<?php echo $this->url($route,array('id'=>$id,'lang'=>$lang,'page'=>$this->next));?>">Next</a></li>
        <?php endif;?>
</ul>
  <?php  endif; ?>