<option value=""><a href="<?php echo $this->url('category',array('id'=>$id,'page'=>$curPage));?>">
        <span><?php echo $this->translate('each page show 5 items');?></span></a>
</option>
<option value=""><a href="<?php echo $this->url('category',array('id'=>$id,'page'=>$curPage));?>">
        <span><?php echo $this->translate('each page show 10 items');?></span></a>
</option>
<option value=""><a href="<?php echo $this->url('category',array('id'=>$id,'page'=>$curPage));?>">
        <span><?php echo $this->translate('each page show 15 items');?></span></a>
</option>
<option value=""><a href="<?php echo $this->url('category',array('id'=>$id,'page'=>$curPage));?>">
        <span><?php echo $this->translate('each page show 20 items');?></span></a>
</option>
<option value=""><a href="<?php echo $this->url('category',array('id'=>$id,'page'=>$curPage));?>">
        <span><?php echo $this->translate('show all items');?></span></a>
</option>